# Generated by Django 5.1.4 on 2024-12-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=10)),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
