# Generated by Django 5.1.4 on 2024-12-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_taskboard_enddate_alter_taskboard_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboard',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
