# Generated by Django 5.1.4 on 2025-01-28 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_prioritymodel_statusmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskboard',
            old_name='task',
            new_name='taskname',
        ),
        migrations.AddField(
            model_name='taskboard',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='status',
            field=models.IntegerField(),
        ),
    ]
