# Generated by Django 5.1.4 on 2025-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_task_taskboard_taskname_taskboard_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboard',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
