# Generated by Django 5.1.4 on 2025-01-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_taskboard_enddate_alter_taskboard_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskboard',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='taskboard',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
