# Generated by Django 5.1.4 on 2025-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_enddate_taskboard_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboard',
            name='priority',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='status',
            field=models.BigIntegerField(),
        ),
    ]
