# Generated by Django 5.1.4 on 2025-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_taskboard_priority_alter_taskboard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskboard',
            name='priority',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
    ]
