# Generated by Django 5.1.4 on 2025-01-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_taskboard_priority_alter_taskboard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskboard',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='taskboard',
            name='status',
        ),
    ]
