# Generated by Django 5.1.4 on 2025-01-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_taskboard_priority_remove_taskboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboard',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
    ]
