# Generated by Django 5.1.4 on 2025-01-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_taskboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboard',
            name='priority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='myapp.prioritymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskboard',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.statusmodel'),
        ),
    ]
