# Generated by Django 5.1.4 on 2025-01-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_taskboard_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskboard',
            old_name='user_id',
            new_name='user',
        ),
    ]
