# Generated by Django 5.1.4 on 2025-01-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_user_id_taskboard_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskboard',
            old_name='user',
            new_name='user_id',
        ),
    ]
